spring:
  application:
    name: ms-directory
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306}/${DB_NAME:wffmain}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:wffmain}
    password: ${DB_PASS:wffmain}
  jpa:
    show-sql: true
    open-in-view: true
  liquibase:
    drop-first: false
    enabled: true
    change-log: classpath:db/changelog.xml

springdoc:
  swagger-ui:
    tags-sorter: alpha
    doc-expansion: none
    operations-sorter: method

server:
  port: ${SERVER_PORT:8080}


